### ISSUE TITLE
Removed some of the views discussed earlier with Carlos.

### ISSUE THREAD

**Issue by crazydog115** [giftcardzen/trustev#1]
_From @danielboros on May 27, 2014 20:28_

All in Admin:
- Removed Merchants#index and replaced with Merchant#stats view.
- Added the Add a Merchant button to the top of the Merchant#stats view and removed AJAX call.
- Reorganized some partials and some existing code into partials.

Additionally, considered removing the Merchants#show view or some things from it, but found it was coupled to the Buckets views so I think this is enough for now.

_Copied from original issue: giftcardzen/main-app/pull/123_

**Comment by crazydog115** [comment]
_From @danielboros on May 27, 2014 20:36_

Need to update the integration tests for this.

**Comment by gabrieljoelc** [comment]
Is this supposed to be in this repo?

**Comment by crazydog115** [comment]
Was testing the issue mover a few days ago with this. Oops!
