### ISSUE TITLE
The api_url is always using v1.2

### ISSUE THREAD

**Issue by IslamAzab** [giftcardzen/trustev#2]
How is the api_version changed ? [src](https://github.com/giftcardzen/trustev/blob/cf9c4af0a4ce901ed9d8b7369473e3cfb631b870/lib/trustev.rb#L19)

**Comment by crazydog115** [comment]
What version of the API do you want to use?

[This branch](https://github.com/giftcardzen/trustev/tree/v2) supports version 2.0 of the API. There is also documentation for version 2.0 of the api on [the wiki](https://github.com/giftcardzen/trustev/wiki).

**Comment by IslamAzab** [comment]
@crazydog115 Yes, I noticed that branch later. However there is no release of the gem that is using the latest updates in that branch, that''s why I created a pull request to try to change the version on master. What do you think?

**Comment by crazydog115** [comment]
Changing the version like in #3 would not work - the API itself has changed significantly. 

If you would like, I can create a pre-release of version 2.0, but I cannot guarantee any functionality.

**Comment by IslamAzab** [comment]
@crazydog115 OK, I will close the pull request then. I would really appreciate the pre-release version.

**Comment by crazydog115** [comment]
Pushed version [0.4.0-alpha](https://rubygems.org/gems/trustev/versions/0.4.0.pre.alpha)
